version: '3.6'

services:
  mongo:
    image: mongo:3.7
    ports:
      - "27017:27017"
      - "28017:28017"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    command: mongod  --smallfiles --logpath=/dev/null
